services:
  db:
    image: postgres:15.5
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5432:5432

  server:
    build: .
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/JWT_test_task
    entrypoint: /usr/src/JWT_test_task/entrypoint.sh
    command: python manage.py runserver 0.0.0.0:8000

  redis:
    image: redis:alpine
    volumes:
      - "redis:/data/"

volumes:
  redis:
  postgres_data:



