# Generated by Django 5.1.7 on 2025-03-27 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_for_both_roles', models.CharField(max_length=255)),
                ('content_for_one_role', models.CharField(max_length=255)),
            ],
        ),
    ]
